# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'remotecode' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for remotecode

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'remotecodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'remotecode-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for remotecode-tvOS

  target 'remotecode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
